import type { ProductKind } from '@prisma/client';

/** Sections alignées sur https://danielcraft.fr/autres-prestations */
export type PrestationSectionId =
	| 'identity'
	| 'ai'
	| 'technical'
	| 'site'
	| 'maintenance'
	| 'offers';

export type PrestationSeed = {
	section: PrestationSectionId;
	name: string;
	sku: string;
	kind: ProductKind;
	unitPrice: number;
	category: string;
	purpose?: string;
	languages?: string[];
	estimatedHours?: number | null;
	description: string;
	details: string[];
	iconName: string;
	visualType?: 'icon' | 'library' | 'custom';
	imageData?: string;
};

export const PRESTATION_SECTIONS: Record<
	PrestationSectionId,
	{ label: string; subtitle: string }
> = {
	identity: {
		label: 'Identité & visibilité',
		subtitle: 'Identité web multi-supports, SEO Google et découvrabilité IA (ChatGPT).',
	},
	ai: {
		label: 'Intelligence artificielle & ChatGPT',
		subtitle: 'Assistants, automatisation, contenus et évolutions IA.',
	},
	technical: {
		label: 'Technique & intégration',
		subtitle: 'Architecture, CRM, migrations, API et performances.',
	},
	site: {
		label: 'Site & contenu',
		subtitle: 'Pages, formulaires, refonte légère et mises à jour.',
	},
	maintenance: {
		label: 'Maintenance & support',
		subtitle: 'Hébergement, sécurité, dépannage et accompagnement.',
	},
	offers: {
		label: 'Offres principales',
		subtitle: 'Sites, applications métier et packs complémentaires.',
	},
};

/** Catalogue DanielCraft — budgets indicatifs du site (mai 2026). */
export const DANIELCRAFT_PRESTATIONS: PrestationSeed[] = [
	// --- Offres principales (hors page « autres prestations » mais liées) ---
	{
		section: 'offers',
		name: 'Site Vitrine',
		sku: 'SITE-VITRINE',
		kind: 'SERVICE',
		unitPrice: 490,
		category: 'THEME',
		purpose: 'SHOWCASE',
		languages: ['HTML', 'CSS', 'JavaScript'],
		estimatedHours: 40,
		description:
			'Site vitrine responsive : design, intégration, contenu de base, formulaire de contact. Base propre pour une identité web cohérente.',
		details: ['Design responsive', 'Formulaire de contact', 'Contenu de base inclus', 'Hébergement non inclus'],
		iconName: 'window-maximize',
		visualType: 'library',
		imageData: 'library:web',
	},
	{
		section: 'offers',
		name: 'Applications métier & automatisation',
		sku: 'AUTO-METIER',
		kind: 'SERVICE',
		unitPrice: 750,
		category: 'DEV',
		purpose: 'SAAS',
		languages: ['TypeScript', 'React', 'NestJS', 'Node.js'],
		estimatedHours: 60,
		description: "Développement d'une application ou d'outils d'automatisation sur mesure.",
		details: ['Workflows sur mesure', 'Intégrations API', 'Scripts métier'],
		iconName: 'code',
		visualType: 'library',
		imageData: 'library:api',
	},
	{
		section: 'offers',
		name: 'Audit & Optimisation',
		sku: 'AUDIT-OPTIM',
		kind: 'SERVICE',
		unitPrice: 650,
		category: 'SEO',
		purpose: 'WEBSITE',
		estimatedHours: 16,
		description:
			'Audit présence web : technique, performances, SEO, sécurité, UX. Rapport et plan d\'action.',
		details: ['Performances & Core Web Vitals', 'SEO & sécurité', 'Plan d\'action priorisé'],
		iconName: 'magnifying-glass',
		visualType: 'library',
		imageData: 'library:analytics',
	},
	{
		section: 'offers',
		name: 'Pack SEO (Google + ChatGPT)',
		sku: 'PACK-SEO-GOOGLE-CHATGPT',
		kind: 'SERVICE',
		unitPrice: 699,
		category: 'SEO',
		purpose: 'WEBSITE',
		estimatedHours: 16,
		description:
			'Pack visibilité : SEO basique + SEO ChatGPT. Idéal commerces et artisans.',
		details: ['Audit Google', 'Données structurées', 'FAQ adaptée à l\'IA'],
		iconName: 'chart-line',
		visualType: 'library',
		imageData: 'library:seo',
	},
	// --- Identité & visibilité ---
	{
		section: 'identity',
		name: "Transformation d'identité web (multi-supports)",
		sku: 'IDENTITE-MULTI',
		kind: 'SERVICE',
		unitPrice: 990,
		category: 'THEME',
		purpose: 'WEBSITE',
		estimatedHours: 24,
		description:
			'Refonte cohérente de votre identité sur site, réseaux sociaux et documents. Une identité unifiée partout où vous êtes visible.',
		details: ['Site + réseaux + documents', 'Charte & gabarits', 'Cohérence multi-supports'],
		iconName: 'palette',
		visualType: 'library',
		imageData: 'library:design',
	},
	{
		section: 'identity',
		name: 'SEO basique (audit + corrections)',
		sku: 'SEO-BASIQUE',
		kind: 'SERVICE',
		unitPrice: 290,
		category: 'SEO',
		purpose: 'WEBSITE',
		estimatedHours: 8,
		description:
			'Audit SEO et corrections pour renforcer votre visibilité sur Google et la cohérence de votre identité en ligne.',
		details: ['Balises & structure', 'Contenu optimisé', 'Corrections ciblées'],
		iconName: 'magnifying-glass',
		visualType: 'library',
		imageData: 'library:seo',
	},
	{
		section: 'identity',
		name: 'SEO pour ChatGPT / découvrabilité IA',
		sku: 'SEO-CHATGPT',
		kind: 'SERVICE',
		unitPrice: 490,
		category: 'SEO',
		purpose: 'WEBSITE',
		estimatedHours: 10,
		description:
			'Optimisation pour que ChatGPT et autres assistants IA citent et recommandent votre marque.',
		details: ['Schema.org', 'FAQ adaptée IA', 'Contenus clairs pour assistants'],
		iconName: 'cloud',
		visualType: 'library',
		imageData: 'library:saas',
	},
	// --- IA & ChatGPT ---
	{
		section: 'ai',
		name: 'Assistant IA FAQ pour site web',
		sku: 'IA-FAQ-SITE',
		kind: 'SERVICE',
		unitPrice: 990,
		category: 'CONTENT',
		purpose: 'WEBSITE',
		languages: ['JavaScript', 'TypeScript', 'ChatGPT API'],
		estimatedHours: 20,
		description:
			'Chatbot sur votre site qui répond aux questions de vos visiteurs grâce à l\'IA.',
		details: ['Installation & configuration', 'Personnalisation', 'Formation incluse'],
		iconName: 'headset',
		visualType: 'library',
		imageData: 'library:saas',
	},
	{
		section: 'ai',
		name: 'Assistant IA support client / email',
		sku: 'IA-SUPPORT-EMAIL',
		kind: 'SERVICE',
		unitPrice: 1200,
		category: 'DEV',
		purpose: 'SAAS',
		languages: ['Python', 'ChatGPT API'],
		estimatedHours: 25,
		description:
			'Automatisation de vos réponses emails avec un assistant IA qui apprend de vos échanges.',
		details: ['Analyse emails existants', 'Templates professionnels', 'Intégration boîte mail'],
		iconName: 'envelope',
		visualType: 'library',
		imageData: 'library:saas',
	},
	{
		section: 'ai',
		name: 'Générateur de contenus web par IA',
		sku: 'IA-CONTENUS-WEB',
		kind: 'SERVICE',
		unitPrice: 650,
		category: 'CONTENT',
		purpose: 'WEBSITE',
		languages: ['ChatGPT API'],
		estimatedHours: 12,
		description:
			'Création de contenus pour votre site (articles, descriptions) par l\'IA, optimisés SEO.',
		details: ['10–15 contenus', 'Ton de marque', 'Révision incluse'],
		iconName: 'pen-nib',
		visualType: 'library',
		imageData: 'library:design',
	},
	{
		section: 'ai',
		name: 'Assistant IA rédaction commerciale',
		sku: 'IA-REDACTION-COMMERCIALE',
		kind: 'SERVICE',
		unitPrice: 490,
		category: 'CONTENT',
		purpose: 'WEBSITE',
		languages: ['ChatGPT API'],
		estimatedHours: 10,
		description:
			'Génère vos emails commerciaux, devis, propositions et messages LinkedIn à partir de votre offre.',
		details: ['Templates sur mesure', 'Interface web', 'Formation'],
		iconName: 'briefcase',
		visualType: 'library',
		imageData: 'library:saas',
	},
	{
		section: 'ai',
		name: 'Analyse de données avec IA',
		sku: 'IA-ANALYSE-DONNEES',
		kind: 'SERVICE',
		unitPrice: 1450,
		category: 'DEV',
		purpose: 'SAAS',
		languages: ['Python', 'ChatGPT API'],
		estimatedHours: 30,
		description:
			'Système d\'analyse de vos données métier avec rapports intelligents et recommandations automatiques.',
		details: ['Tableau de bord', 'Rapports mensuels', 'Détection tendances & anomalies'],
		iconName: 'chart-line',
		visualType: 'library',
		imageData: 'library:analytics',
	},
	{
		section: 'ai',
		name: 'Chatbot IA e-commerce',
		sku: 'IA-CHATBOT-ECOMMERCE',
		kind: 'SERVICE',
		unitPrice: 1600,
		category: 'ECOMMERCE',
		purpose: 'ECOMMERCE',
		languages: ['JavaScript', 'ChatGPT API', 'TypeScript'],
		estimatedHours: 35,
		description:
			'Assistant conversationnel pour votre boutique : questions produits, recommandations, aide commande.',
		details: ['Connexion catalogue', 'Scénarios de vente', 'Personnalisation'],
		iconName: 'cart-shopping',
		visualType: 'library',
		imageData: 'library:ecommerce',
	},
	{
		section: 'ai',
		name: 'Automatisation de tâches avec IA',
		sku: 'IA-AUTOMATISATION-TACHES',
		kind: 'SERVICE',
		unitPrice: 1200,
		category: 'DEV',
		purpose: 'SAAS',
		languages: ['Python', 'ChatGPT API'],
		estimatedHours: 25,
		description:
			'Automatisation de tâches répétitives (tri emails, classification, extraction, rapports) grâce à l\'IA.',
		details: ['Audit processus', 'Scripts IA', 'Documentation & support'],
		iconName: 'gear',
		visualType: 'library',
		imageData: 'library:api',
	},
	{
		section: 'ai',
		name: 'Maintenance mensuelle assistant IA',
		sku: 'IA-MAINTENANCE-MENSUEL',
		kind: 'SAAS',
		unitPrice: 75,
		category: 'MAINTENANCE',
		purpose: 'SAAS',
		estimatedHours: 2,
		description:
			'Ajustement des réponses, nouvelles connaissances, optimisation. Abonnement mensuel.',
		details: ['Mises à jour connaissances', 'Optimisation performances', 'Suivi mensuel'],
		iconName: 'wrench',
		visualType: 'library',
		imageData: 'library:saas',
	},
	{
		section: 'ai',
		name: 'Évolution fonctionnalités IA',
		sku: 'IA-EVOLUTION-FEATURE',
		kind: 'SERVICE',
		unitPrice: 330,
		category: 'DEV',
		purpose: 'SAAS',
		languages: ['ChatGPT API'],
		estimatedHours: 6,
		description:
			'Ajout d\'une fonctionnalité à votre assistant IA existant (intégration outil, nouvelle source de données).',
		details: ['À partir de 330 €', 'Intégration tierce', 'Nouvelle source de données'],
		iconName: 'puzzle-piece',
		visualType: 'library',
		imageData: 'library:api',
	},
	{
		section: 'ai',
		name: 'Audit utilisation IA',
		sku: 'IA-AUDIT-USAGE',
		kind: 'SERVICE',
		unitPrice: 400,
		category: 'SEO',
		purpose: 'SAAS',
		estimatedHours: 8,
		description:
			'Audit de votre usage de l\'IA pour identifier des opportunités d\'amélioration et nouveaux cas d\'usage.',
		details: ['Revue outils existants', 'Recommandations concrètes', 'Rapport détaillé'],
		iconName: 'lightbulb',
		visualType: 'library',
		imageData: 'library:analytics',
	},
	// --- Technique & intégration ---
	{
		section: 'technical',
		name: 'Conseil technique / architecture',
		sku: 'CONSEIL-ARCHI',
		kind: 'SERVICE',
		unitPrice: 380,
		category: 'DEV',
		purpose: 'WEBSITE',
		estimatedHours: 8,
		description:
			'Étude de faisabilité, choix des technologies, architecture cible, estimation coûts et délais.',
		details: ['Rapport de conseil', 'Plan d\'action', 'Estimation projet'],
		iconName: 'lightbulb',
		visualType: 'library',
		imageData: 'library:api',
	},
	{
		section: 'technical',
		name: 'Intégration CRM ou outil métier',
		sku: 'INTEG-CRM',
		kind: 'SERVICE',
		unitPrice: 290,
		category: 'API',
		purpose: 'WEBSITE',
		languages: ['TypeScript', 'Node.js'],
		estimatedHours: 10,
		description:
			'Connexion de votre site ou app à un CRM, outil de facturation ou logiciel métier.',
		details: ['Sync données', 'Webhooks', 'API sur mesure'],
		iconName: 'plug',
		visualType: 'library',
		imageData: 'library:api',
	},
	{
		section: 'technical',
		name: 'Script de migration de données',
		sku: 'MIGRATION-DONNEES',
		kind: 'SERVICE',
		unitPrice: 330,
		category: 'DEV',
		purpose: 'WEBSITE',
		languages: ['Python', 'TypeScript'],
		estimatedHours: 12,
		description:
			'Migration de données d\'un système à un autre (Excel vers BDD, ancien CMS vers nouveau).',
		details: ['Script sécurisé', 'Traçabilité', 'Vérification des données'],
		iconName: 'database',
		visualType: 'library',
		imageData: 'library:api',
	},
	{
		section: 'technical',
		name: 'Intégration API / webhook',
		sku: 'INTEG-API',
		kind: 'SERVICE',
		unitPrice: 150,
		category: 'API',
		purpose: 'WEBSITE',
		languages: ['TypeScript', 'Node.js'],
		estimatedHours: 6,
		description:
			'Connexion à une API tierce ou mise en place de webhooks pour synchronisation et automatisations.',
		details: ['À partir de 150 €', 'Sync temps réel', 'Automatisations'],
		iconName: 'plug',
		visualType: 'library',
		imageData: 'library:api',
	},
	{
		section: 'technical',
		name: 'Rapport de performances (one-shot)',
		sku: 'RAPPORT-PERF',
		kind: 'SERVICE',
		unitPrice: 120,
		category: 'SEO',
		purpose: 'WEBSITE',
		estimatedHours: 3,
		description:
			'Analyse des performances (Core Web Vitals, temps de chargement) et rapport avec recommandations.',
		details: ['Core Web Vitals', 'Recommandations actionnables', 'Livrable PDF'],
		iconName: 'rocket',
		visualType: 'library',
		imageData: 'library:analytics',
	},
	// --- Site & contenu ---
	{
		section: 'site',
		name: 'Page supplémentaire (site vitrine)',
		sku: 'PAGE-SUPP',
		kind: 'SERVICE',
		unitPrice: 65,
		category: 'CONTENT',
		purpose: 'SHOWCASE',
		languages: ['HTML', 'CSS'],
		estimatedHours: 2,
		description:
			'Ajout d\'une page au site vitrine : structure, contenu, mise en forme.',
		details: ['Par page', 'Mise en forme incluse', 'Responsive'],
		iconName: 'file-code',
		visualType: 'library',
		imageData: 'library:web',
	},
	{
		section: 'site',
		name: 'Formulaire avancé / intégration',
		sku: 'FORM-AVANCE',
		kind: 'SERVICE',
		unitPrice: 99,
		category: 'DEV',
		purpose: 'SHOWCASE',
		languages: ['JavaScript'],
		estimatedHours: 4,
		description:
			'Formulaire avancé avec validation, envoi par email, export ou connexion CRM.',
		details: ['Validation', 'Email ou CRM', 'Export données'],
		iconName: 'envelope',
		visualType: 'library',
		imageData: 'library:web',
	},
	{
		section: 'site',
		name: 'Refonte visuelle légère',
		sku: 'REFONTE-LEGERE',
		kind: 'SERVICE',
		unitPrice: 330,
		category: 'THEME',
		purpose: 'SHOWCASE',
		languages: ['HTML', 'CSS', 'JavaScript'],
		estimatedHours: 12,
		description:
			'Refonte du design (couleurs, typo, mise en page) sans changer la structure ni le contenu.',
		details: ['Couleurs & typo', 'Mise en page', 'Sans refonte structure'],
		iconName: 'palette',
		visualType: 'library',
		imageData: 'library:design',
	},
	{
		section: 'site',
		name: 'Mise à jour de contenu (pack 5h)',
		sku: 'MAJ-CONTENU-5H',
		kind: 'SERVICE',
		unitPrice: 170,
		category: 'CONTENT',
		purpose: 'SHOWCASE',
		estimatedHours: 5,
		description:
			'Pack 5 heures pour mises à jour de textes, images et pages sur votre site.',
		details: ['Pack 5 h', 'Textes & images', 'Pages existantes'],
		iconName: 'pen-nib',
		visualType: 'library',
		imageData: 'library:web',
	},
	{
		section: 'site',
		name: "Formation à l'outil (demi-journée)",
		sku: 'FORMATION-DEMI',
		kind: 'SERVICE',
		unitPrice: 200,
		category: 'CONTENT',
		purpose: 'WEBSITE',
		estimatedHours: 4,
		description:
			'Session de formation (demi-journée) à la prise en main de votre outil ou site.',
		details: ['Back-office', 'Publication', 'Bonnes pratiques'],
		iconName: 'users',
		visualType: 'library',
		imageData: 'library:web',
	},
	// --- Maintenance & support ---
	{
		section: 'maintenance',
		name: 'Maintenance site (mensuelle)',
		sku: 'MAINT-MENSUEL',
		kind: 'SERVICE',
		unitPrice: 39,
		category: 'MAINTENANCE',
		purpose: 'WEBSITE',
		estimatedHours: 2,
		description:
			'Mises à jour de sécurité, sauvegardes, surveillance et corrections mineures.',
		details: ['Mensuel', 'Sauvegardes', 'Corrections mineures'],
		iconName: 'wrench',
		visualType: 'library',
		imageData: 'library:hosting',
	},
	{
		section: 'maintenance',
		name: 'Hébergement + nom de domaine (annuel)',
		sku: 'HEBERG-DOMAIN',
		kind: 'SERVICE',
		unitPrice: 79,
		category: 'HOSTING',
		purpose: 'WEBSITE',
		estimatedHours: 1,
		description:
			'Hébergement web annuel + enregistrement ou renouvellement d\'un nom de domaine.',
		details: ['Annuel', '.fr ou .com', 'Renouvellement domaine'],
		iconName: 'server',
		visualType: 'library',
		imageData: 'library:hosting',
	},
	{
		section: 'maintenance',
		name: 'Backup & sécurisation',
		sku: 'BACKUP-SECU',
		kind: 'SERVICE',
		unitPrice: 99,
		category: 'MAINTENANCE',
		purpose: 'WEBSITE',
		estimatedHours: 4,
		description:
			'Sauvegardes automatiques, renforcement de la sécurité (SSL, headers, bonnes pratiques).',
		details: ['Sauvegardes auto', 'SSL & headers', 'Bonnes pratiques'],
		iconName: 'shield-halved',
		visualType: 'library',
		imageData: 'library:security',
	},
	{
		section: 'maintenance',
		name: 'Certificat SSL + configuration',
		sku: 'SSL-CONFIG',
		kind: 'SERVICE',
		unitPrice: 45,
		category: 'HOSTING',
		purpose: 'WEBSITE',
		estimatedHours: 1,
		description:
			'Installation et configuration d\'un certificat SSL (HTTPS) sur votre hébergement.',
		details: ['HTTPS', 'Configuration serveur', 'One-shot'],
		iconName: 'lock',
		visualType: 'library',
		imageData: 'library:security',
	},
	{
		section: 'maintenance',
		name: 'Support / Abonnement',
		sku: 'SUPPORT-ABO',
		kind: 'SAAS',
		unitPrice: 25,
		category: 'MAINTENANCE',
		purpose: 'WEBSITE',
		estimatedHours: null,
		description:
			'Assistance par email, mises à jour mineures, suivi technique mensuel.',
		details: ['Mensuel 25 €', 'Email', 'Mises à jour mineures'],
		iconName: 'headset',
		visualType: 'library',
		imageData: 'library:support',
	},
	{
		section: 'maintenance',
		name: 'Dépannage / intervention (forfait 2h)',
		sku: 'DEPANNAGE-2H',
		kind: 'SERVICE',
		unitPrice: 120,
		category: 'MAINTENANCE',
		purpose: 'WEBSITE',
		estimatedHours: 2,
		description:
			'Forfait 2 heures pour dépannage ou intervention technique (bug, correctif, petite évolution).',
		details: ['Forfait 2 h', 'Bug & correctif', 'Petite évolution'],
		iconName: 'screwdriver-wrench',
		visualType: 'library',
		imageData: 'library:support',
	},
	{
		section: 'maintenance',
		name: 'Accompagnement technique (heure)',
		sku: 'ACCOMP-H',
		kind: 'SERVICE',
		unitPrice: 60,
		category: 'MAINTENANCE',
		purpose: 'WEBSITE',
		languages: ['TypeScript', 'React', 'NestJS'],
		estimatedHours: 1,
		description:
			'Conseil, débogage, revue de code, aide à la mise en place d\'une fonctionnalité.',
		details: ['À l\'heure 60 €', 'Débogage', 'Revue de code'],
		iconName: 'code',
		visualType: 'library',
		imageData: 'library:support',
	},
	{
		section: 'maintenance',
		name: 'Support prioritaire (heure)',
		sku: 'SUPPORT-H',
		kind: 'SERVICE',
		unitPrice: 70,
		category: 'MAINTENANCE',
		purpose: 'WEBSITE',
		estimatedHours: 1,
		description:
			'Réponse rapide, intervention ciblée, résolution de blocage.',
		details: ['À l\'heure 70 €', 'Réponse rapide', 'Blocage résolu'],
		iconName: 'bell',
		visualType: 'library',
		imageData: 'library:support',
	},
];

export const SKU_TO_SECTION: Record<string, PrestationSectionId> = Object.fromEntries(
	DANIELCRAFT_PRESTATIONS.map(p => [p.sku, p.section])
);
