import type { DevProductSeed } from './dev-product.types';

/**
 * Catalogue v2 — produits = livrables par stack (pas une liste plate de micro-prestations).
 * Chaque entrée décrit ce que le client reçoit et l'assemblage techno associé.
 */
export const DEV_PRODUCTS: DevProductSeed[] = [
	// ─── Entrée junior / premier client ─────────────────────────────────────
	{
		sku: 'STACK-WEB-STATIC',
		name: 'Site vitrine statique',
		kind: 'SERVICE',
		unitPrice: 490,
		category: 'THEME',
		purpose: 'SHOWCASE',
		profile: 'junior',
		assembly: { languages: ['HTML', 'CSS', 'JavaScript'] },
		estimatedHours: 40,
		description:
			'Site vitrine responsive : design, intégration, formulaire contact. Stack web standard, repo Git inclus.',
		details: ['5 pages', 'Responsive', 'Formulaire contact', 'SEO de base'],
		iconName: 'window-maximize',
		visualType: 'library',
		imageData: 'library:web',
	},
	{
		sku: 'STACK-WP-VITRINE',
		name: 'Site WordPress sur mesure',
		kind: 'SERVICE',
		unitPrice: 450,
		category: 'THEME',
		purpose: 'SHOWCASE',
		profile: 'junior',
		assembly: { languages: ['PHP'], cms: ['WordPress'] },
		estimatedHours: 20,
		description: 'Thème enfant WordPress : gabarits, champs ACF, mise en production.',
		details: ['Thème enfant', 'Back-office', 'Plugins essentiels', 'Formation courte'],
		iconName: 'store',
		visualType: 'library',
		imageData: 'library:marketplace',
	},
	// ─── Offres métier (peu techniques) ─────────────────────────────────────
	{
		sku: 'OFFRE-VITRINE-CLAIR',
		name: 'Site vitrine clé en main',
		kind: 'SERVICE',
		unitPrice: 420,
		category: 'THEME',
		purpose: 'SHOWCASE',
		profile: 'junior',
		assembly: { languages: ['HTML', 'CSS', 'JavaScript'] },
		estimatedHours: 32,
		description:
			'Site vitrine pour TPE / artisan : pages essentielles, design soigné, formulaire contact, livraison clé en main.',
		details: ['Jusqu’à 5 pages', 'Responsive', 'Formulaire contact', 'Passation client'],
		iconName: 'window-maximize',
		visualType: 'library',
		imageData: 'library:forms',
	},
	{
		sku: 'OFFRE-CONSEIL-WEB',
		name: 'Conseil présence en ligne',
		kind: 'SERVICE',
		unitPrice: 180,
		category: 'CONSULTING',
		purpose: 'WEBSITE',
		profile: 'junior',
		assembly: { languages: ['HTML', 'CSS'] },
		estimatedHours: 3,
		description:
			'Appel + mini audit : positionnement, pages indispensables, priorités et estimation réaliste du projet.',
		details: ['1 h visio', 'Recommandations', 'Priorisation', 'Estimation'],
		iconName: 'lightbulb',
		visualType: 'library',
		imageData: 'library:crm',
	},
	{
		sku: 'OFFRE-REDACTION-WEB',
		name: 'Rédaction de pages web',
		kind: 'SERVICE',
		unitPrice: 120,
		category: 'COPYWRITING',
		purpose: 'SHOWCASE',
		profile: 'junior',
		assembly: { languages: ['HTML', 'CSS'] },
		estimatedHours: 4,
		description: 'Rédaction orientée client : accueil, services, à propos — ton adapté à votre cible.',
		details: ['Par page', 'Ton de marque', 'Relecture incluse'],
		iconName: 'pen-nib',
		visualType: 'library',
		imageData: 'library:newsletter',
	},
	{
		sku: 'OFFRE-CHARTE-GRAPHIQUE',
		name: 'Charte graphique légère',
		kind: 'SERVICE',
		unitPrice: 350,
		category: 'DESIGN',
		purpose: 'SHOWCASE',
		profile: 'junior',
		assembly: { languages: ['HTML', 'CSS'] },
		estimatedHours: 12,
		description: 'Logo simplifié ou déclinaisons, palette, typos et gabarits pour votre site.',
		details: ['Palette & typos', 'Gabarits', 'Export assets'],
		iconName: 'palette',
		visualType: 'library',
		imageData: 'library:design',
	},
	{
		sku: 'OFFRE-HANDOVER',
		name: 'Mise en ligne & passation client',
		kind: 'SERVICE',
		unitPrice: 150,
		category: 'SETUP',
		purpose: 'WEBSITE',
		profile: 'junior',
		assembly: { languages: ['HTML', 'CSS', 'JavaScript'] },
		estimatedHours: 4,
		description: 'Domaine, mise en production, check-list de livraison et session de prise en main.',
		details: ['Mise en ligne', 'Check-list', 'Session passation'],
		iconName: 'calendar-check',
		visualType: 'library',
		imageData: 'library:booking',
	},
	{
		sku: 'OFFRE-BILAN-SITE',
		name: 'Bilan express de votre site',
		kind: 'SERVICE',
		unitPrice: 190,
		category: 'AUDIT',
		purpose: 'WEBSITE',
		profile: 'junior',
		assembly: { languages: ['HTML', 'CSS', 'JavaScript'] },
		estimatedHours: 5,
		description: 'État des lieux rapide : UX, perf, SEO de base et 5 actions prioritaires.',
		details: ['Rapport court', '5 actions', 'Visio de restitution'],
		iconName: 'comments',
		visualType: 'library',
		imageData: 'library:dashboard',
	},
	{
		sku: 'OFFRE-FORMULE-SERENITE',
		name: 'Formule sérénité (mensuel)',
		kind: 'SAAS',
		unitPrice: 35,
		category: 'SUPPORT',
		purpose: 'WEBSITE',
		profile: 'junior',
		assembly: { languages: ['HTML', 'CSS', 'JavaScript'] },
		estimatedHours: null,
		description: 'Suivi mensuel : petites corrections, conseils et point de contact dédié.',
		details: ['Mensuel', 'Corrections mineures', 'Point mensuel'],
		iconName: 'headset',
		visualType: 'library',
		imageData: 'library:support',
	},
	{
		sku: 'STACK-NEXT-LANDING',
		name: 'Landing Next.js + Vercel',
		kind: 'SERVICE',
		unitPrice: 590,
		category: 'DEV',
		purpose: 'SHOWCASE',
		profile: 'junior',
		assembly: {
			languages: ['TypeScript'],
			frontend: ['React', 'Next.js'],
			devops: ['Vercel'],
		},
		estimatedHours: 24,
		description: 'Landing marketing Next.js : SSR, formulaire, déploiement Vercel et domaine custom.',
		details: ['Next.js App Router', 'Vercel preview/prod', 'Analytics de base'],
		iconName: 'rocket',
		visualType: 'library',
		imageData: 'library:web',
	},

	// ─── Full-stack TypeScript ───────────────────────────────────────────────
	{
		sku: 'STACK-MVP-REACT-NEST',
		name: 'MVP SaaS React + NestJS',
		kind: 'SERVICE',
		unitPrice: 750,
		category: 'DEV',
		purpose: 'SAAS',
		profile: 'standard',
		assembly: {
			languages: ['TypeScript'],
			frontend: ['React'],
			backend: ['NestJS', 'Node.js'],
			databases: ['PostgreSQL'],
		},
		estimatedHours: 60,
		description:
			'Application métier ou MVP SaaS : auth, CRUD, API REST, dashboard React, base PostgreSQL.',
		details: ['Auth JWT', 'API REST documentée', 'Dashboard admin', 'Tests de base'],
		iconName: 'briefcase',
		visualType: 'library',
		imageData: 'library:saas',
	},
	{
		sku: 'STACK-NEXT-SUPABASE',
		name: 'App Next.js + Supabase',
		kind: 'SERVICE',
		unitPrice: 680,
		category: 'DEV',
		purpose: 'SAAS',
		profile: 'junior',
		assembly: {
			languages: ['TypeScript'],
			frontend: ['React', 'Next.js'],
			databases: ['Supabase', 'PostgreSQL'],
			devops: ['Vercel'],
		},
		estimatedHours: 45,
		description: 'SaaS léger : auth Supabase, tables RLS, front Next.js, déploiement Vercel.',
		details: ['RLS Supabase', 'Auth email/OAuth', 'Déploiement Vercel'],
		iconName: 'puzzle-piece',
		visualType: 'library',
		imageData: 'library:dashboard',
	},
	{
		sku: 'STACK-API-GRAPHQL-TS',
		name: 'API GraphQL TypeScript',
		kind: 'SERVICE',
		unitPrice: 520,
		category: 'API',
		purpose: 'SAAS',
		profile: 'standard',
		assembly: {
			languages: ['TypeScript'],
			backend: ['NestJS', 'Node.js', 'GraphQL'],
			databases: ['PostgreSQL'],
		},
		estimatedHours: 28,
		description: 'Schéma GraphQL typé, resolvers NestJS, auth et documentation pour votre front.',
		details: ['Schéma typé', 'Resolvers', 'Playground / doc'],
		iconName: 'layer-group',
		visualType: 'library',
		imageData: 'library:api',
	},

	// ─── Vue / Nuxt ────────────────────────────────────────────────────────
	{
		sku: 'STACK-NUXT-SITE',
		name: 'Site Nuxt 3',
		kind: 'SERVICE',
		unitPrice: 720,
		category: 'DEV',
		purpose: 'SHOWCASE',
		profile: 'standard',
		assembly: {
			languages: ['TypeScript', 'JavaScript'],
			frontend: ['Vue.js', 'Nuxt'],
		},
		estimatedHours: 40,
		description: 'Site ou mini-app Nuxt 3 : SSR/SSG, composants, formulaires, SEO.',
		details: ['SSR ou SSG', 'Composables', 'SEO technique'],
		iconName: 'tag',
		visualType: 'library',
		imageData: 'library:web',
	},
	{
		sku: 'STACK-VUE-DASHBOARD',
		name: 'Dashboard Vue 3 + API',
		kind: 'SERVICE',
		unitPrice: 890,
		category: 'DEV',
		purpose: 'SAAS',
		profile: 'standard',
		assembly: {
			languages: ['TypeScript'],
			frontend: ['Vue.js'],
			backend: ['Node.js', 'REST API'],
		},
		estimatedHours: 50,
		description: 'Interface admin Vue 3 connectée à votre API : tableaux, formulaires, état Pinia.',
		details: ['Vue 3 + Pinia', 'Connexion API', 'Composants réutilisables'],
		iconName: 'chart-line',
		visualType: 'library',
		imageData: 'library:web',
	},

	// ─── PHP / CMS ─────────────────────────────────────────────────────────
	{
		sku: 'STACK-LARAVEL-APP',
		name: 'Application Laravel',
		kind: 'SERVICE',
		unitPrice: 780,
		category: 'DEV',
		purpose: 'SAAS',
		profile: 'standard',
		assembly: {
			languages: ['PHP'],
			backend: ['Laravel'],
			databases: ['MySQL'],
		},
		estimatedHours: 48,
		description: 'App métier Laravel : modèles, contrôleurs, auth, API ou Blade selon besoin.',
		details: ['MVC Laravel', 'Migrations', 'Auth & rôles'],
		iconName: 'file-invoice',
		visualType: 'library',
		imageData: 'library:migration',
	},
	{
		sku: 'STACK-PRESTASHOP-BOUTIQUE',
		name: 'Boutique PrestaShop',
		kind: 'SERVICE',
		unitPrice: 590,
		category: 'ECOMMERCE',
		purpose: 'ECOMMERCE',
		profile: 'standard',
		assembly: { languages: ['PHP'], cms: ['PrestaShop'] },
		estimatedHours: 28,
		description: 'Installation, thème et paramétrage catalogue / paiement / livraison PrestaShop.',
		details: ['Catalogue', 'Paiement', 'Livraison'],
		iconName: 'truck',
		visualType: 'library',
		imageData: 'library:marketplace',
	},
	{
		sku: 'STACK-SHOPIFY-THEME',
		name: 'Thème Shopify custom',
		kind: 'SERVICE',
		unitPrice: 520,
		category: 'ECOMMERCE',
		purpose: 'ECOMMERCE',
		profile: 'standard',
		assembly: { languages: ['JavaScript'], cms: ['Shopify'] },
		estimatedHours: 18,
		description: 'Personnalisation thème Shopify (Liquid), sections et apps essentielles.',
		details: ['Liquid', 'Sections', 'Apps Shopify'],
		iconName: 'cart-shopping',
		visualType: 'library',
		imageData: 'library:ecommerce',
	},

	// ─── Python ────────────────────────────────────────────────────────────
	{
		sku: 'STACK-FASTAPI-API',
		name: 'API FastAPI + PostgreSQL',
		kind: 'SERVICE',
		unitPrice: 620,
		category: 'API',
		purpose: 'SAAS',
		profile: 'junior',
		assembly: {
			languages: ['Python'],
			backend: ['FastAPI'],
			databases: ['PostgreSQL'],
		},
		estimatedHours: 32,
		description: 'API REST FastAPI documentée OpenAPI, auth, connexion PostgreSQL, tests pytest.',
		details: ['OpenAPI / Swagger', 'Auth', 'Tests pytest'],
		iconName: 'satellite-dish',
		visualType: 'library',
		imageData: 'library:automation',
	},
	{
		sku: 'STACK-DJANGO-PORTAL',
		name: 'Portail Django',
		kind: 'SERVICE',
		unitPrice: 850,
		category: 'DEV',
		purpose: 'SAAS',
		profile: 'standard',
		assembly: {
			languages: ['Python'],
			backend: ['Django'],
			databases: ['PostgreSQL'],
		},
		estimatedHours: 55,
		description: 'Portail métier Django : admin, modèles, permissions, templates ou API DRF.',
		details: ['Admin Django', 'ORM & migrations', 'Permissions'],
		iconName: 'code',
		visualType: 'library',
		imageData: 'library:api',
	},
	{
		sku: 'STACK-RAG-LANGCHAIN',
		name: 'Agent RAG LangChain',
		kind: 'SERVICE',
		unitPrice: 1100,
		category: 'DEV',
		purpose: 'SAAS',
		profile: 'expert',
		assembly: {
			languages: ['Python'],
			ai: ['LangChain', 'OpenAI'],
			databases: ['PostgreSQL'],
		},
		estimatedHours: 28,
		description: 'Pipeline RAG : ingestion documents, embeddings, recherche vectorielle, réponses sourcées.',
		details: ['Ingestion docs', 'Vector store', 'Évaluation qualité'],
		iconName: 'wand-magic-sparkles',
		visualType: 'library',
		imageData: 'library:ai-assistant',
	},

	// ─── Mobile ────────────────────────────────────────────────────────────
	{
		sku: 'STACK-RN-APP',
		name: 'App React Native + API',
		kind: 'SERVICE',
		unitPrice: 1200,
		category: 'DEV',
		purpose: 'SAAS',
		profile: 'standard',
		assembly: {
			languages: ['TypeScript'],
			frontend: ['React'],
			mobile: ['React Native'],
			backend: ['REST API'],
		},
		estimatedHours: 70,
		description: 'Application iOS/Android React Native : écrans, navigation, connexion API backend.',
		details: ['Expo ou bare', 'Stores', 'API backend'],
		iconName: 'mobile-screen',
		visualType: 'library',
		imageData: 'library:web',
	},
	{
		sku: 'STACK-FLUTTER-APP',
		name: 'App Flutter cross-platform',
		kind: 'SERVICE',
		unitPrice: 1100,
		category: 'DEV',
		purpose: 'SAAS',
		profile: 'standard',
		assembly: {
			languages: ['Dart'],
			mobile: ['Flutter'],
			backend: ['REST API'],
		},
		estimatedHours: 65,
		description: 'App Flutter Material/Cupertino, state management, publication stores.',
		details: ['UI native', 'API', 'Build release'],
		iconName: 'mobile-screen',
		visualType: 'library',
		imageData: 'library:web',
	},

	// ─── IA & automatisation ───────────────────────────────────────────────
	{
		sku: 'STACK-CHATBOT-WEB',
		name: 'Chatbot IA sur site',
		kind: 'SERVICE',
		unitPrice: 990,
		category: 'DEV',
		purpose: 'WEBSITE',
		profile: 'junior',
		assembly: {
			languages: ['JavaScript', 'TypeScript'],
			ai: ['OpenAI'],
		},
		estimatedHours: 20,
		description: 'Widget chatbot sur votre site : FAQ, personnalisation ton de marque, garde-fous.',
		details: ['Widget intégré', 'Base connaissances', 'Formation'],
		iconName: 'robot',
		visualType: 'library',
		imageData: 'library:ai-assistant',
	},
	{
		sku: 'STACK-N8N-WORKFLOW',
		name: 'Automatisation n8n',
		kind: 'SERVICE',
		unitPrice: 450,
		category: 'DEV',
		purpose: 'SAAS',
		profile: 'junior',
		assembly: { ai: ['n8n'], backend: ['REST API'] },
		estimatedHours: 12,
		description: 'Scénarios n8n entre CRM, email, sheets et APIs — documentation et gestion erreurs.',
		details: ['Scénarios', 'Retry & alertes', 'Documentation'],
		iconName: 'arrows-rotate',
		visualType: 'library',
		imageData: 'library:automation',
	},
	{
		sku: 'STACK-CLAUDE-INTEG',
		name: 'Intégration Claude API',
		kind: 'SERVICE',
		unitPrice: 890,
		category: 'DEV',
		purpose: 'SAAS',
		profile: 'standard',
		assembly: {
			languages: ['Python', 'TypeScript'],
			ai: ['Claude', 'Anthropic'],
		},
		estimatedHours: 18,
		description: 'Connexion Anthropic Claude dans votre app ou workflow interne avec garde-fous.',
		details: ['API Anthropic', 'Prompts', 'Limites & logs'],
		iconName: 'comments',
		visualType: 'library',
		imageData: 'library:ai-assistant',
	},

	// ─── DevOps ────────────────────────────────────────────────────────────
	{
		sku: 'STACK-DOCKER-CICD',
		name: 'Docker + CI/CD GitHub Actions',
		kind: 'SERVICE',
		unitPrice: 380,
		category: 'HOSTING',
		purpose: 'SAAS',
		profile: 'junior',
		assembly: {
			devops: ['Docker', 'GitHub Actions', 'CI/CD'],
		},
		estimatedHours: 14,
		description: 'Dockerfile, compose, pipeline GitHub Actions : lint, tests, build, déploiement.',
		details: ['Image optimisée', 'Workflow YAML', 'Secrets CI'],
		iconName: 'rocket',
		visualType: 'library',
		imageData: 'library:monitoring',
	},
	{
		sku: 'STACK-K8S-DEPLOY',
		name: 'Déploiement Kubernetes',
		kind: 'SERVICE',
		unitPrice: 450,
		category: 'HOSTING',
		purpose: 'SAAS',
		profile: 'expert',
		assembly: {
			devops: ['Kubernetes', 'Docker', 'Nginx'],
		},
		estimatedHours: 14,
		description: 'Manifests K8s, ingress, secrets, déploiement rolling documenté.',
		details: ['Deployments', 'Ingress', 'Secrets'],
		iconName: 'gauge-high',
		visualType: 'library',
		imageData: 'library:hosting',
	},
	{
		sku: 'STACK-AWS-LIGHT',
		name: 'Infra AWS légère',
		kind: 'SERVICE',
		unitPrice: 380,
		category: 'HOSTING',
		purpose: 'SAAS',
		profile: 'standard',
		assembly: {
			devops: ['AWS', 'Docker'],
		},
		estimatedHours: 12,
		description: 'EC2, S3 ou RDS selon besoin — schéma infra simple et estimation coûts.',
		details: ['Schéma infra', 'Coûts estimés', 'Sécurité de base'],
		iconName: 'satellite-dish',
		visualType: 'library',
		imageData: 'library:hosting',
	},

	// ─── Sécurité ──────────────────────────────────────────────────────────
	{
		sku: 'STACK-AUDIT-SECU',
		name: 'Audit sécurité & performances',
		kind: 'SERVICE',
		unitPrice: 650,
		category: 'SEO',
		purpose: 'WEBSITE',
		profile: 'standard',
		assembly: {
			languages: ['HTML', 'JavaScript'],
			security: ['OWASP'],
		},
		estimatedHours: 16,
		description: 'Audit technique, performances, OWASP Top 10, plan d\'action priorisé.',
		details: ['Core Web Vitals', 'OWASP', 'Rapport actionnable'],
		iconName: 'magnifying-glass',
		visualType: 'library',
		imageData: 'library:analytics',
	},
	{
		sku: 'STACK-PENTEST-APP',
		name: 'Pentest application',
		kind: 'SERVICE',
		unitPrice: 850,
		category: 'MAINTENANCE',
		purpose: 'WEBSITE',
		profile: 'expert',
		assembly: { security: ['OWASP', 'pentest'] },
		estimatedHours: 16,
		description: 'Tests d\'intrusion applicatifs manuels, rapport et plan de remédiation.',
		details: ['OWASP Top 10', 'Tests manuels', 'Remédiation'],
		iconName: 'shield-halved',
		visualType: 'library',
		imageData: 'library:security',
	},

	// ─── Récurrent & add-ons (budget maîtrisé) ─────────────────────────────
	{
		sku: 'STACK-MAINT-MENSUEL',
		name: 'Maintenance site mensuelle',
		kind: 'SERVICE',
		unitPrice: 39,
		category: 'MAINTENANCE',
		purpose: 'WEBSITE',
		profile: 'junior',
		assembly: {
			languages: ['HTML', 'CSS', 'JavaScript', 'PHP'],
			devops: ['Nginx'],
		},
		estimatedHours: 2,
		description: 'Mises à jour sécurité, sauvegardes, surveillance et corrections mineures.',
		details: ['Mensuel', 'Sauvegardes', 'Corrections mineures'],
		iconName: 'wrench',
		visualType: 'library',
		imageData: 'library:hosting',
	},
	{
		sku: 'STACK-SUPPORT-ABO',
		name: 'Support / abonnement',
		kind: 'SAAS',
		unitPrice: 25,
		category: 'MAINTENANCE',
		purpose: 'WEBSITE',
		profile: 'junior',
		assembly: {
			languages: ['HTML', 'CSS', 'JavaScript'],
		},
		estimatedHours: null,
		description: 'Assistance email, mises à jour mineures, suivi technique mensuel.',
		details: ['Mensuel 25 €', 'Email', 'Mises à jour mineures'],
		iconName: 'headset',
		visualType: 'library',
		imageData: 'library:support',
	},
	{
		sku: 'ADDON-SEO-BASIQUE',
		name: 'SEO basique (audit + corrections)',
		kind: 'SERVICE',
		unitPrice: 290,
		category: 'SEO',
		purpose: 'WEBSITE',
		profile: 'junior',
		assembly: { languages: ['HTML', 'CSS', 'JavaScript'] },
		estimatedHours: 8,
		description: 'Audit SEO et corrections ciblées pour Google.',
		details: ['Balises & structure', 'Contenu', 'Corrections'],
		iconName: 'magnifying-glass',
		visualType: 'library',
		imageData: 'library:seo',
	},
	{
		sku: 'ADDON-PAGE-SUPP',
		name: 'Page supplémentaire',
		kind: 'SERVICE',
		unitPrice: 65,
		category: 'CONTENT',
		purpose: 'SHOWCASE',
		profile: 'junior',
		assembly: { languages: ['HTML', 'CSS'] },
		estimatedHours: 2,
		description: 'Ajout d\'une page au site : structure, contenu, mise en forme responsive.',
		details: ['Par page', 'Responsive', 'Mise en forme'],
		iconName: 'file-code',
		visualType: 'library',
		imageData: 'library:web',
	},
	{
		sku: 'ADDON-DEPANNAGE-2H',
		name: 'Dépannage (forfait 2 h)',
		kind: 'SERVICE',
		unitPrice: 120,
		category: 'MAINTENANCE',
		purpose: 'WEBSITE',
		profile: 'junior',
		assembly: {
			languages: ['HTML', 'CSS', 'JavaScript', 'PHP'],
		},
		estimatedHours: 2,
		description: 'Bug, correctif ou petite évolution — forfait 2 heures.',
		details: ['Forfait 2 h', 'Bug & correctif', 'Petite évolution'],
		iconName: 'screwdriver-wrench',
		visualType: 'library',
		imageData: 'library:support',
	},
	{
		sku: 'ADDON-ACCOMP-H',
		name: 'Accompagnement technique (heure)',
		kind: 'SERVICE',
		unitPrice: 60,
		category: 'MAINTENANCE',
		purpose: 'WEBSITE',
		profile: 'junior',
		assembly: {
			languages: ['TypeScript'],
			frontend: ['React'],
			backend: ['NestJS'],
		},
		estimatedHours: 1,
		description: 'Débogage, revue de code, aide mise en place d\'une fonctionnalité.',
		details: ['À l\'heure', 'Débogage', 'Revue de code'],
		iconName: 'code',
		visualType: 'library',
		imageData: 'library:support',
	},
	{
		sku: 'ADDON-FORMATION',
		name: 'Formation (demi-journée)',
		kind: 'SERVICE',
		unitPrice: 200,
		category: 'CONTENT',
		purpose: 'WEBSITE',
		profile: 'junior',
		assembly: {
			languages: ['HTML', 'CSS', 'JavaScript'],
		},
		estimatedHours: 4,
		description: 'Session de prise en main de votre site ou outil (back-office, bonnes pratiques).',
		details: ['Demi-journée', 'Back-office', 'Bonnes pratiques'],
		iconName: 'users',
		visualType: 'library',
		imageData: 'library:booking',
	},
];

/** Alias historiques pour seeds démo (devis, abonnements). */
export const DEV_PRODUCT_ALIASES = {
	siteVitrine: 'STACK-WEB-STATIC',
	automatisation: 'STACK-MVP-REACT-NEST',
	auditOptim: 'STACK-AUDIT-SECU',
	supportAbo: 'STACK-SUPPORT-ABO',
} as const;
