import { PrismaClient } from '@prisma/client';
import type { SeedContext } from './base.seed';

export async function seedProspects(prisma: PrismaClient): Promise<void> {
	const prospects = [
		{
			companyName: 'TechStartup Inc',
			industry: 'SaaS',
			size: 'STARTUP',
			website: 'https://techstartup.com',
			email: 'contact@techstartup.com',
			phone: '+33 1 23 45 67 89',
			address: '123 Rue de l\'Innovation',
			city: 'Paris',
			country: 'France',
			revenue: 500000,
			employees: 15,
			description: 'Startup spécialisée dans l\'IA pour PME',
			painPoints: JSON.stringify(['Manque de visibilité', 'Difficulté de recrutement']),
			budget: 'MEDIUM',
			decisionMakerName: 'Marie Dupont',
			decisionMakerPosition: 'CEO',
			decisionMakerEmail: 'marie@techstartup.com',
			decisionMakerLinkedin: 'linkedin.com/in/mariedupont',
			status: 'QUALIFIED',
			sourceType: 'PAID',
			sourceName: 'LinkedIn Ads',
			sourceCost: 150,
			sourceConversionRate: 2.5,
			score: 85,
			priority: 'HIGH',
			assignedTo: 'sales1',
			lastContact: new Date('2024-01-15'),
			nextFollowUp: new Date('2024-01-22'),
			notes: JSON.stringify(['Intéressé par notre solution de facturation', 'Budget disponible Q1 2024']),
			tags: JSON.stringify(['SaaS', 'IA', 'PME'])
		},
		{
			companyName: 'Digital Agency Pro',
			industry: 'Marketing',
			size: 'SMALL',
			website: 'https://digitalagency.com',
			email: 'hello@digitalagency.com',
			phone: '+33 1 98 76 54 32',
			address: '45 Avenue des Champs',
			city: 'Lyon',
			country: 'France',
			revenue: 250000,
			employees: 8,
			description: 'Agence digitale spécialisée en e-commerce',
			painPoints: JSON.stringify(['Gestion de la facturation', 'Suivi des paiements']),
			budget: 'MEDIUM',
			decisionMakerName: 'Pierre Martin',
			decisionMakerPosition: 'Directeur',
			decisionMakerEmail: 'pierre@digitalagency.com',
			status: 'CONTACTED',
			sourceType: 'ORGANIC',
			sourceName: 'Site web',
			score: 70,
			priority: 'MEDIUM',
			notes: JSON.stringify(['Premier contact effectué', 'Démo prévue la semaine prochaine']),
			tags: JSON.stringify(['Marketing', 'E-commerce'])
		},
		{
			companyName: 'Consulting Experts',
			industry: 'Conseil',
			size: 'MEDIUM',
			website: 'https://consultingexperts.fr',
			email: 'info@consultingexperts.fr',
			phone: '+33 1 11 22 33 44',
			address: '78 Boulevard Haussmann',
			city: 'Paris',
			country: 'France',
			revenue: 1200000,
			employees: 25,
			description: 'Cabinet de conseil en stratégie',
			budget: 'HIGH',
			decisionMakerName: 'Sophie Bernard',
			decisionMakerPosition: 'Directrice Financière',
			decisionMakerEmail: 'sophie@consultingexperts.fr',
			status: 'PROPOSAL',
			sourceType: 'REFERRAL',
			sourceName: 'Recommandation client',
			score: 90,
			priority: 'HIGH',
			lastContact: new Date(),
			nextFollowUp: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
			notes: JSON.stringify(['Proposition envoyée', 'Décision attendue sous 2 semaines']),
			tags: JSON.stringify(['Conseil', 'Stratégie'])
		},
		{
			companyName: 'E-commerce Solutions',
			industry: 'E-commerce',
			size: 'LARGE',
			website: 'https://ecommercesolutions.com',
			email: 'contact@ecommercesolutions.com',
			phone: '+33 1 55 66 77 88',
			address: '100 Rue du Commerce',
			city: 'Lille',
			country: 'France',
			revenue: 5000000,
			employees: 120,
			description: 'Plateforme e-commerce B2B et B2C',
			budget: 'ENTERPRISE',
			decisionMakerName: 'Thomas Leroy',
			decisionMakerPosition: 'CTO',
			decisionMakerEmail: 'thomas@ecommercesolutions.com',
			status: 'NEGOTIATION',
			sourceType: 'EVENT',
			sourceName: 'Salon e-commerce Paris',
			score: 95,
			priority: 'URGENT',
			lastContact: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
			nextFollowUp: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
			notes: JSON.stringify(['Négociation en cours', 'Besoin urgent de solution']),
			tags: JSON.stringify(['E-commerce', 'Enterprise'])
		},
		{
			companyName: 'WebDev Studio',
			industry: 'Développement',
			size: 'SMALL',
			website: 'https://webdevstudio.fr',
			email: 'bonjour@webdevstudio.fr',
			phone: '+33 4 12 34 56 78',
			address: '25 Rue du Code',
			city: 'Toulouse',
			country: 'France',
			revenue: 180000,
			employees: 5,
			description: 'Studio de développement web et mobile',
			budget: 'LOW',
			decisionMakerName: 'Alexandre Moreau',
			decisionMakerPosition: 'Fondateur',
			decisionMakerEmail: 'alex@webdevstudio.fr',
			status: 'NEW',
			sourceType: 'SOCIAL',
			sourceName: 'Twitter',
			score: 60,
			priority: 'LOW',
			notes: JSON.stringify(['Nouveau prospect', 'À contacter']),
			tags: JSON.stringify(['Développement', 'Web'])
		},
		{
			companyName: 'Finance Corp',
			industry: 'Finance',
			size: 'ENTERPRISE',
			website: 'https://financecorp.com',
			email: 'info@financecorp.com',
			phone: '+33 1 99 88 77 66',
			address: '200 Avenue des Finances',
			city: 'Paris',
			country: 'France',
			revenue: 50000000,
			employees: 500,
			description: 'Groupe financier international',
			budget: 'ENTERPRISE',
			decisionMakerName: 'Catherine Dubois',
			decisionMakerPosition: 'Directrice Achats',
			decisionMakerEmail: 'c.dubois@financecorp.com',
			status: 'CLOSED_WON',
			sourceType: 'PARTNERSHIP',
			sourceName: 'Partenariat stratégique',
			score: 100,
			priority: 'HIGH',
			lastContact: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
			notes: JSON.stringify(['Contrat signé', 'Démarrage prévu Q2']),
			tags: JSON.stringify(['Finance', 'Enterprise', 'Won'])
		}
	];

	for (const prospect of prospects) {
		await prisma.prospect.create({
			data: prospect as any
		});
	}
}

