-- Droits sur tables/sequences créées par postgres (migrations manuelles ou CREATE TABLE IF NOT EXISTS)
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO facturio;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO facturio;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO facturio;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO facturio;
